[tool.cibuildwheel]
# specify build architectures for each platform
build = [
  "cp39-*",
  "cp310-*",
  "cp311-*",
  "cp312-*",
  "cp313-*",
]


# skip unsupported target architectures
skip = [
  "*-win32",
  "*-manylinux_i686",
  "*-musllinux*"
]

# automatically use host platform architecture
archs = "auto"

# automatically use host platform architecture for each platform
[tool.cibuildwheel.windows]
archs = ["AMD64"]

[tool.cibuildwheel.linux]
archs = ["x86_64"]

# specify macOS architectures, including x86_64 and arm64, so that the 2 binary packages support these 2 architectures
# because the libssp library on macOS only has x86_64 and arm64 architectures, no universal version
[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

# skip testing
test-skip = "*"

